version: '3'

services:
  #  cookie池容器
  cookie_pool:
    container_name: cookie_pool
    build: .
    restart: always
    ports:
      - "5020:5020"
    depends_on:
      - selenium
  #  selenium+Chrome容器
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"