version: '3'

services:

  cookie_pool:
    container_name: cookie_pool
    build: .
    restart: always
    ports:
      - "5020:5020"
    depends_on:
      - selenium_cookie

  selenium_cookie:
    container_name: selenium_cookie
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"