version: '2'
services:
  proxy_pool:
    build: .
    ports:
      - "5020:5020"
    links:
      - proxy_redis
    environment:
      db_type: SSDB
      ssdb_host: proxy_redis
      ssdb_port: 6379
  proxy_redis:
    image: "redis"