version: '2'
services:
  cookie_pool:
    build: .
    ports:
      - "5020:5020"
    links:
      - cookie_redis
    environment:
      db_type: SSDB
      ssdb_host: cookie_redis
      ssdb_port: 6379
  cookie_redis:
    image: "redis"